name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  flutter_native_splash: 2.4.7
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_lints: ^5.0.0
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
flutter_native_splash:
  color: "#FFFFFF" # This is white
  image: assets/images/logo.jpg


  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.jpg

  web: true